---
abstract: Easy interface to IO::Pty
author: 'Jesse Luehrs, C<< <jluehrs2 at uiuc dot edu> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IO-Pty-Easy
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  IO::Pty: 0
version: 0.03
